-- Clear existing data
DELETE FROM products;

-- Reset sequence
ALTER SEQUENCE products_id_seq RESTART WITH 1;

-- Insert sample products
INSERT INTO products (name, description, price, image_url, thumbnail_url, active, stock) VALUES
                                                                                             ('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 109.95, 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', TRUE, 120),
                                                                                             ('Mens Casual Premium Slim Fit T-Shirts', 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 22.3, 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', TRUE, 259),
                                                                                             ('Mens Cotton Jacket', 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 55.99, 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', TRUE, 500),
                                                                                             ('Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', 15.99, 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', TRUE, 430),
                                                                                             ('John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', 695.00, 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', TRUE, 400),
                                                                                             ('Solid Gold Petite Micropave', 'Satisfaction Guaranteed. Return or exchange any order within 30 days. Designed and sold by Hafeez Center in the United States.', 168.00, 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', TRUE, 70),
                                                                                             ('White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...', 9.99, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', TRUE, 400),
                                                                                             ('Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 10.99, 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', TRUE, 100),
                                                                                             ('WD 2TB Elements Portable External Hard Drive - USB 3.0', 'USB 3.0 and USB 2.0 Compatibility. Fast data transfers. Improve PC Performance. High Capacity.', 64.00, 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', TRUE, 203),
                                                                                             ('SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'Easy upgrade for faster boot up, shutdown, application load and response.', 109.00, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', TRUE, 470),
                                                                                             ('Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '3D NAND flash are applied to deliver high transfer speeds. Remarkable transfer speeds enable faster bootup and improved system performance.', 109.00, 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', TRUE, 319),
                                                                                             ('WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience. Play anywhere. Sleek design. 3-year warranty.', 114.00, 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', TRUE, 400),
                                                                                             ('Acer SB220Q bi 21.5 inches Full HD IPS Ultra-Thin', '21.5 inches Full HD (1920x1080) IPS display. Radeon FreeSync technology.', 599.00, 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', TRUE, 250),
                                                                                             ('Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor', '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side. QLED HDR support.', 999.99, 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', TRUE, 140),
                                                                                             ('BIYLACLESEN Women''s 3-in-1 Snowboard Jacket', 'US standard size. Material: 100% Polyester. Detachable liner with warm fleece.', 56.99, 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', TRUE, 235),
                                                                                             ('Lock and Love Women''s Faux Leather Moto Biker Jacket', 'Faux leather for style and comfort. Removable hood. Machine washable.', 29.95, 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', TRUE, 340),
                                                                                             ('Rain Jacket Women Windbreaker', 'Lightweight and perfect for trips or casual wear. Long sleeve with hood and adjustable waist.', 39.99, 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', TRUE, 679),
                                                                                             ('MBJ Women''s Solid Short Sleeve Boat Neck V', '95% RAYON 5% SPANDEX. Lightweight with great stretch.', 9.85, 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', TRUE, 130),
                                                                                             ('Opna Women''s Short Sleeve Moisture', '100% cationic polyester interlock. Pre-shrunk. Machine washable.', 7.95, 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', TRUE, 146),
                                                                                             ('DANVOUY Womens T Shirt Casual Cotton Short', '95% Cotton, 5% Spandex. Soft with some stretch. Letter print and V-neck.', 12.99, 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', TRUE, 145);